accelerator:
  displayName: Dotnet Blazor Accelerator
  description: Dotnet Blazor with best practices like health and info endpoint
  iconUrl: https://icons.iconarchive.com/icons/thesquid.ink/free-flat-sample/96/space-rocket-icon.png
  tags:
  - simple
  - getting-started
  - DotNet
