apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-dotnet-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-dotnet-web-app
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/ykhadilkar/tanzu-dotnet-web-app
      ref:
        branch: main