apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blazor-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: blazor-app
    apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: blazor-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: language
    value: dotnet
  source:
    git:
      url: https://github.com/ykhadilkar/BlazorApp
      ref:
        branch: master
